[32mâœ“[0m Connected to cloud
2024-05-05 23:38:09,131 - INFO - Location: [32mUk[0m, Day: [35m0[0m, Check digits: [36m933704[0m
2024-05-05 23:38:21,642 - INFO - Location: [32mUk[0m, Day: [35m1[0m, Check digits: [36m531652[0m
2024-05-05 23:41:27,085 - INFO - Location: [32mohio[0m, Day: [35m0[0m, Check digits: [36m717715[0m
2024-05-05 23:41:35,559 - INFO - Location: [32mohio[0m, Day: [35m1[0m, Check digits: [36m789721[0m
2024-05-05 23:41:41,978 - INFO - Location: [32mohio[0m, Day: [35m2[0m, Check digits: [36m232425[0m
2024-05-05 23:41:49,066 - INFO - Location: [32mohio[0m, Day: [35m3[0m, Check digits: [36m292220[0m
2024-05-05 23:41:55,099 - INFO - Location: [32mohio[0m, Day: [35m3[0m, Check digits: [36m922204[0m
2024-05-05 23:47:01,688 - INFO - Location: [32mOrust[0m, Day: [35m0[0m, Check digits: [36m255774[0m
2024-05-05 23:47:18,827 - INFO - Location: [32mOrust[0m, Day: [35m1[0m, Check digits: [36m127143[0m
2024-05-05 23:47:56,540 - INFO - Location: [32mSan Fransisco[0m, Day: [35m0[0m, Check digits: [36m130333[0m
2024-05-05 23:54:01,216 - INFO - Location: [32mMumbai[0m, Day: [35m0[0m, Check digits: [36m518439[0m
2024-05-05 23:54:23,347 - INFO - Location: [32mMumbai[0m, Day: [35m1[0m, Check digits: [36m900971[0m
2024-05-05 23:54:38,864 - INFO - Location: [32mEarth[0m, Day: [35m0[0m, Check digits: [36m464910[0m
2024-05-05 23:54:47,196 - INFO - Location: [32mEarth[0m, Day: [35m1[0m, Check digits: [36m644774[0m
2024-05-05 23:54:56,382 - INFO - Location: [32mAntarctica[0m, Day: [35m0[0m, Check digits: [36m802854[0m
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weather.py", line 177, in <module>
    cwdata, code = currentweather(location, checkdigits)
  File "weather.py", line 55, in currentweather
    data, code = weather(location)
  File "weather.py", line 42, in weather
    json = response.json()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
