[32mâœ“[0m Connected to cloud
2024-05-05 22:55:50,359 - INFO - Location: [32msydney[0m, Day: [35m0[0m, Check digits: [36m821065[0m
2024-05-05 22:55:55,430 - INFO - Location: [32mSan Fransisco[0m, Day: [35m0[0m, Check digits: [36m363916[0m
2024-05-05 22:56:00,542 - INFO - Location: [32msydney[0m, Day: [35m1[0m, Check digits: [36m171826[0m
2024-05-05 22:56:06,532 - INFO - Location: [32mSan Fransisco[0m, Day: [35m1[0m, Check digits: [36m577533[0m
2024-05-05 22:56:25,224 - INFO - Location: [32mlive[0m, Day: [35m0[0m, Check digits: [36m867776[0m
2024-05-05 22:56:32,597 - INFO - Location: [32mlive[0m, Day: [35m1[0m, Check digits: [36m290333[0m
2024-05-05 22:58:27,255 - INFO - Location: [32mMelbourne[0m, Day: [35m0[0m, Check digits: [36m854666[0m
2024-05-05 23:06:43,082 - INFO - Location: [32mst Austell [0m, Day: [35m0[0m, Check digits: [36m422637[0m
2024-05-05 23:06:58,428 - INFO - Location: [32mst Austell [0m, Day: [35m1[0m, Check digits: [36m630256[0m
2024-05-05 23:07:08,661 - INFO - Location: [32mst Austell [0m, Day: [35m2[0m, Check digits: [36m797097[0m
2024-05-05 23:07:17,852 - INFO - Location: [32mst Austell [0m, Day: [35m3[0m, Check digits: [36m170525[0m
2024-05-05 23:07:24,009 - INFO - Location: [32mst Austell [0m, Day: [35m2[0m, Check digits: [36m174828[0m
2024-05-05 23:07:30,039 - INFO - Location: [32mst Austell [0m, Day: [35m1[0m, Check digits: [36m649706[0m
2024-05-05 23:07:36,060 - INFO - Location: [32mst Austell [0m, Day: [35m0[0m, Check digits: [36m237053[0m
2024-05-05 23:07:43,180 - INFO - Location: [32mst Austell [0m, Day: [35m0[0m, Check digits: [36m745080[0m
2024-05-05 23:09:00,989 - INFO - Location: [32mst Austell [0m, Day: [35m1[0m, Check digits: [36m381817[0m
2024-05-05 23:11:23,202 - INFO - Location: [32m~bodmin jail[0m, Day: [35m0[0m, Check digits: [36m389987[0m
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python3.7/site-packages/simplejson/decoder.py", line 393, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weather.py", line 177, in <module>
    cwdata, code = currentweather(location, checkdigits)
  File "weather.py", line 55, in currentweather
    data, code = weather(location)
  File "weather.py", line 42, in weather
    json = response.json()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
